#!/usr/bin/env ruby

require "erb"
require "redcarpet"
require "ostruct"

$markdown = Redcarpet::Markdown.new(
  Redcarpet::Render::HTML.new,
  autolink: true,
  space_after_headers: true,
  footnotes: true
)

INDEX_TEMPLATE = File.read("templates/index.html.erb")
JOBS_TEMPLATE = File.read("templates/jobs.html.erb")
UPDATE_TEMPLATE = File.read("templates/update.html.erb")
TEAM_TEMPLATE = File.read("templates/team.html.erb")

def page!(template, name, out, src, extra)
  contents = File.read(src)
  attrs = { name: name, body: $markdown.render(contents) }
  attrs.merge!(extra || {})
  result = to_html(template, attrs)
  File.new("#{out}.html", "w").write(result)
end

def to_html(template, attrs)
  ERB.new(template).result(OpenStruct.new(attrs).instance_eval { binding })
end

page! INDEX_TEMPLATE, "index", "index", "intro.md", {}
page! JOBS_TEMPLATE, "jobs", "jobs", "jobs.md", {}
page! TEAM_TEMPLATE, "team", "team", "team.md", {}

[1, 2].each do |n|
  page! UPDATE_TEMPLATE, "update", "updates/#{n}", "updates/#{n}.md", { n: n }
end
