#!/usr/bin/env ruby

require "erb"
require "redcarpet"
require "ostruct"

$markdown = Redcarpet::Markdown.new(
  Redcarpet::Render::HTML.new(hard_wrap: true),
  autolink: true,
  space_after_headers: true,
  footnotes: true
)

INDEX_TEMPLATE = File.read("templates/index.html.erb")
JOBS_TEMPLATE = File.read("templates/jobs.html.erb")

def page!(template, name, path)
  contents = File.read(path)
  attrs = { name: name, body: $markdown.render(contents) }
  result = to_html(template, attrs)
  File.new("#{name}.html", "w").write(result)
end

def to_html(template, attrs)
  ERB.new(template).result(OpenStruct.new(attrs).instance_eval { binding })
end

page! INDEX_TEMPLATE, "index", "intro.md"
page! JOBS_TEMPLATE, "jobs", "jobs.md"
